### ISSUE TITLE
engine.ps1 fails 

### ISSUE THREAD

**Issue by exbane** [WahlNetwork/grafana-vsphere-lab#1]
Good afternoon,

I've followed your blog on setting up influxdb,grafana, and your powershell scripts.. I have the grafana server and influxdb server all setup and ready to go.. I'm having a problem with the engine.ps1 script though.

My system that i have powercli on is a server 2012 R2 VM with PowerCLI 6 installed (i tried with v5.5 too) i commented out the SQL and veeam collectors in the config file since i dont use them. I configured the vars.ps1 file with my vcenter server to collect from and this is the following output when I attempt to run the script.

PowerCLI D:\grafana-vsphere-lab-master\grafana-vsphere-lab-master> .\engine.ps1

Id     Name            PSJobTypeName   State         HasMoreData     Location

---

2      Hosts           BackgroundJob   Running       True            localhost
4      VMs             BackgroundJob   Running       True            localhost

Id Name  PSJobTypeName State  HasMoreData Location  Command

---

2  Hosts BackgroundJob Failed True        localhost ...
4  VMs   BackgroundJob Failed True        localhost ...

It states that it fails for some reason but doesnt provide any logging as to what the problem is.. I can connect to the vCenter servers via PowerCLI just fine and run commands as normal. Thoughts?

**Comment by chriswahl** [comment]
If you run the job files directly do they work?

**Comment by exbane** [comment]
I'll check and see if they work.. If they don't i'll output the screen to you.
